name: pokedex_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  rxdart: ^0.24.1
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0+1
  pointycastle: ^1.0.2
  sqflite: ^1.3.1+1
  shared_preferences: ^0.5.10
  very_good_analysis: ^1.0.2
  # pedantic: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pokeball.png
    - assets/pokeball2.png
    - assets/ash.png
